#include <iostream>
#include "draw.hpp"

/**
 * TO DO : 
 * LIRE L'IMAGE PNG DE LA MAP POUR SAVOIR QUELS SPRITES METTRE SUR LA MAP DANS LA FENETRE
 * DRAW TOUR
 * DRAW ENNEMI
 * DRAW BOUTON
 * DRAW TOUT LE TEXTE AUTOUR
*/